---
title: "Scratch"
author: "Craig Demke"
date: '2022-06-23'
output: html_document
---

```{r set global chunks, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE, message = FALSE
)
```

```{r load libraries}
library(tidyverse)
library(datasets)
library(plotly)
library(gt)
library(glue)
library(stringr)
library(DT)
library(purrr)
library(here)
library(lubridate)
```
### 

```{r}
library(here)
source(here::here("R", "data_io_util.R"))

student_file <- get_data_from_sql_file(file_name="student_file.sql",
                             dsn="edify")
```

```{r}
term <- '202230'
version <- 'Current'

summer_student_file <- student_file %>% 
  filter(term_id == term & version_desc == version)

#DT::datatable(student_file, rownames=FALSE)
```


function for S-01
```{r}
format_ushe_id <- function(input_df) {
  
  output_df <- input_df
  output_df$ushe_id <- "3671"
  
output_df <- output_df %>% 
  relocate(ushe_id, .before = )
  
  return(output_df)
  
}
```

Function for S-02
```{r}
format_ushe_year_term_extract <- function(input_df) {
  
  output_df <- input_df %>%
    mutate(academic_year = str_sub(term_id, 1, 4)) %>% 
    mutate(last_year = (as.numeric(academic_year) - 1)) %>%
    mutate(season = str_sub(term_id, 5, 6)) %>%  
    mutate(academic_year_code = case_when(
      season == "30" ~ as.character(last_year),
      season == "40" ~ as.character(last_year),
      season == '20' ~ as.character(last_year),
      TRUE ~ "error")) %>% 
    mutate(t_format = case_when(
      season == "30" ~ '1',
      season == "40" ~ '2',
      season == '20' ~ '3',
      TRUE ~ "mistake")) %>% 
    mutate(v_format = case_when(
      version_id == '1' ~ 'current',
      version_id == '2' ~ '3',
      version_id == '3' ~ 'E',
      TRUE ~ "error"))

output_df$"year_term_extract" = paste(output_df$academic_year_code,
                                        output_df$t_format,
                                        output_df$v_format, sep = "")

#output_df$year_term_extract <- gsub('\\s+', '', output_df$"year_term_extract") %>% 
#relocate(year_term_extract, .before)

output_df <- output_df %>%
 relocate(year_term_extract, .before = 2)


return(output_df)
}
```

```{r}

New_student_file <- format_ushe_id(summer_student_file)

New_student_file <- format_ushe_year_term_extract(New_student_file)


```

