## code to prepare `fake_course_df` dataset goes here

sample_size <- 3000

fake_course_df <- data.frame(
  course_reference_number = sample(c("", NA), sample_size, replace = TRUE),
  course_number = sample(c("", NA), sample_size, replace = TRUE),
  subject_code = sample(c("", NA), sample_size, replace = TRUE),
  class_size = sample(c("", NA), sample_size, replace = TRUE),
  budget_code = sample(c("", NA), sample_size, replace = TRUE),
  campus_id = sample(c("", NA), sample_size, replace = TRUE),
  section_number = sample(c("", NA), sample_size, replace = TRUE),
  attribute_code = sample(c("", NA), sample_size, replace = TRUE),
  academic_department_id = sample(c("", NA), sample_size, replace = TRUE),
  college_id = sample(c("", NA), sample_size, replace = TRUE),
  section_format_type_code = sample(c("", NA), sample_size, replace = TRUE),
  instructor_first_name = sample(c("", NA), sample_size, replace = TRUE),
  instructor_last_name = sample(c("", NA), sample_size, replace = TRUE),
  instructor_middle_name = sample(c("", NA), sample_size, replace = TRUE),
  instructor_employee_id = sample(c("", NA), sample_size, replace = TRUE),
  course_title = sample(c("MATH, & ENGL-1010", NA), sample_size, replace = TRUE),
  course_end_date = sample(c("", NA), sample_size, replace = TRUE),
  course_start_date = sample(c("", NA), sample_size, replace = TRUE),
  room_use_code_3 = sample(c("", NA), sample_size, replace = TRUE),
  room_max_occupancy_3 = sample(c("", NA), sample_size, replace = TRUE),
  meet_room_number_3 = sample(c("", NA), sample_size, replace = TRUE),
  building_number_3 = sample(c("", NA), sample_size, replace = TRUE),
  meet_building_id_3 = sample(c("", NA), sample_size, replace = TRUE),
  meet_days_3 = sample(c("", NA), sample_size, replace = TRUE),
  meet_end_time_3 = sample(c("", NA), sample_size, replace = TRUE),
  meet_start_time_3 = sample(c("", NA), sample_size, replace = TRUE),
  room_use_code_2 = sample(c("", NA), sample_size, replace = TRUE),
  room_max_occupancy_2 = sample(c("", NA), sample_size, replace = TRUE),
  meet_room_number_2 = sample(c("", NA), sample_size, replace = TRUE),
  building_number_2 = sample(c("", NA), sample_size, replace = TRUE),
  meet_building_id_2 = sample(c("", NA), sample_size, replace = TRUE),
  meet_days_2 = sample(c("", NA), sample_size, replace = TRUE),
  meet_end_time_2 = sample(c("", NA), sample_size, replace = TRUE),
  meet_start_time_2 = sample(c("", NA), sample_size, replace = TRUE),
  room_use_code_1 = sample(c("", NA), sample_size, replace = TRUE),
  room_max_occupancy_1 = sample(c("", NA), sample_size, replace = TRUE),
  meet_room_number_1 = sample(c("", NA), sample_size, replace = TRUE),
  building_number_1 = sample(c("", NA), sample_size, replace = TRUE),
  meet_building_id_1 = sample(c("", NA), sample_size, replace = TRUE),
  meet_days_1 = sample(c("", NA), sample_size, replace = TRUE),
  meet_end_time_1 = sample(c("", NA), sample_size, replace = TRUE),
  meet_start_time_1 = sample(c("", NA), sample_size, replace = TRUE),
  course_level_id = sample(c("", NA), sample_size, replace = TRUE),
  program_type = sample(c("", NA), sample_size, replace = TRUE),
  instruction_method_code = sample(c("", NA), sample_size, replace = TRUE),
  contact_hours = sample(c("", NA), sample_size, replace = TRUE),
  course_max_credits = sample(c(0.5:8, NA), sample_size, replace = TRUE),
  course_min_credits = sample(c(0.5:8, NA), sample_size, replace = TRUE),
  season = sample(c("", NA), sample_size, replace = TRUE),
  academic_year_code = sample(c("", NA), sample_size, replace = TRUE),
  version_id = sample(c("", NA), sample_size, replace = TRUE)
)

usethis::use_data(fake_course_df, overwrite = TRUE)
