/* Student File with versioning */
   SELECT c.season,
          a.student_id,
          b.ssn AS student_ssn,
          b.ssn AS student_ssid,
          b.previous_student_id,
          b.name_suffix,
          b.last_name,
          b.first_name,
          b.last_name,
          b.middle_name,
          '' AS previous_name_suffix,
          b.previous_last_name,
          b.previous_first_name,
          b.previous_middle_name,
          b.local_address_zip_code,
          b.mailing_address_zip_code,
          b.us_citizenship_code,
          b.first_admit_county_code,
          b.first_admit_state_code,
          b.first_admit_country_code,
          b.birth_date,
          b.gender_code,
          b.is_hispanic_latino_ethnicity,
          b.is_asian,
          b.is_black,
          b.is_american_indian_alaskan,
          b.is_hawaiian_pacific_islander,
          b.is_white,
          b.is_international,
          b.is_other_race,
          a.residency_code,
          a.primary_major_cip_code,
          a.primary_major_desc,
          a.student_type_code,
          a.primary_level_class_id,
          a.primary_degree_id,
          a.institutional_cumulative_credits_earned,
          a.institutional_cumulative_gpa,
          a.institutional_cumulative_gpa AS institutional_gpa,
          COALESCE(a.transfer_cumulative_credits_earned, 0) AS transfer_cumulative_credits_earned,
          a.full_time_part_time_code,
          b.first_admit_country_iso_code,
          a.house_bill_75_waiver,
          a.secondary_major_cip_code,
          a.secondary_major_desc,
          COALESCE(a.total_cumulative_ap_credits_earned, 0) AS total_cumulative_ap_credits_earned,
          COALESCE(a.total_cumulative_clep_credits_earned, 0) AS total_cumulative_clep_credits_earned,
          b.act_composite_score,
          b.act_english_score,
          b.act_math_score,
          b.act_reading_score AS act_read_score,
          b.act_science_score,
          b.high_school_code AS latest_high_school_code,
          b.high_school_desc,
          b.high_school_graduation_date,
          c.term_start_date,
          a.is_pell_eligible,
          a.is_pell_awarded,
          a.is_bia,
          a.primary_major_college_id,
          a.primary_major_college_desc,
          a.secondary_major_college_id,
          a.secondary_major_college_desc,
          a.level_id,
          a.term_id,
          c.academic_year_code AS academic_year,
          b.version_id,
          b.version_desc,
          b.version_date
     FROM export.student_term_level_version a
    LEFT JOIN export.term c
        ON a.term_id = c.term_id
    LEFT JOIN export.student_version b
       ON b.student_id = a.student_id
      AND b.version_snapshot_id = a.version_snapshot_id
    WHERE a.term_id >= (SELECT term_id FROM export.term WHERE is_previous_term)
      AND a.is_primary_level = TRUE
      AND a.is_enrolled = TRUE
 ORDER BY student_id;

