---
title: "G-28  Degree Type Name"
author: "Craig Demke"
date: '2022-07-13'
output: html_document
---

```{r set global chunks, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE, message = FALSE
)
```

```{r load libraries}
library(tidyverse)
library(datasets)
library(plotly)
library(gt)
library(glue)
library(stringr)
library(DT)
library(purrr)
library(here)
```
### This is part of the 
* 

### This data is found in Edify from 
```{}

```


### Create fake data that matches this.

```{r}
g_28_degree_type_name_test_df <- tibble(
  
) %>% 
   

DT::datatable(g_28_degree_type_name_test_df, rownames=FALSE)
```

### Now let's see if we can pull in real data

```{r}
### We pull the data we want from the report database REPT 

g_28_degree_type_name_real_df <- utHelpR::get_data_from_sql_file(file_name="g_28_degree_type_name.sql",
                                               dsn="edify",
                                               context="sandbox")

# display data pulled in table
DT::datatable(g_28_degree_type_name_real_df, rownames=FALSE)
```


### Here is the R script

The first thing I need to do is to figure out how to

```{r}

change_g_28_degree_type_name_df <- g_28_degree_type_name_test_df %>%
    # Calculate intermediate fields
    mutate( intermediate_field_1 = "1") %>%
    mutate( intermediate_field_2 = "2") %>%
    # Append USHE data element s_xx
    mutate( s_xx = paste0(intermediate_field_1, intermediate_field_2) )
  


DT::datatable(change_g_28_degree_type_name_df, rownames=FALSE)



```

### Making a function

```{r}
  
format_g_28_degree_type_name <- function(input_df, with_intermediates=FALSE) {

  output_df <- input_df %>%
    # Calculate intermediate fields
    mutate( intermediate_field_1 = "1") %>%
    mutate( intermediate_field_2 = "2") %>%
    # Append USHE data element s_xx
    mutate( s_xx = paste0(intermediate_field_1, intermediate_field_2) )

    if (!with_intermediates) {
      output_df <- output_df %>%
        # Remove fields used for intermediate calculations
        select( -c(intermediate_field_1, intermediate_field_2) )
    }

  return(output_df)

  
}
```
### Choose which data frame you want pass through the function 

g_28_degree_type_name_test_df for the fake data set
```{r}
DT::datatable(format_g_28_degree_type_name(g_28_degree_type_name_test_df), rownames=FALSE)
```

g_28_degree_type_name_real_df for the real data
```{r}
DT::datatable(format_g_28_degree_type_name(g_28_degree_type_name_real_df), rownames=FALSE)
```
