---
title: "Graduation file"
author: "Craig Demke"
date: '2022-07-12'
output: html_document
---

```{r set global chunks, include=FALSE}
knitr::opts_chunk$set(
  warning = FALSE, message = FALSE
)
```

```{r load libraries}
library(tidyverse)
library(datasets)
library(plotly)
library(gt)
library(glue)
library(stringr)
library(DT)
library(purrr)
library(here)
library(lubridate)
library(readxl)
library(janitor)

```

###  Here we pull the info from edify with the utHelp function
```{r}
graduation_file <- utHelpR::get_data_from_sql_file(file_name="graduation_file.sql",
                                               dsn="edify",
                                               context="sandbox")
```

Now we filter the term and version of the course sql
```{r}
term <- '202220'

scratch_graduation_file <- graduation_file %>% 
  filter(graduated_term_id == term)



#DT::datatable(student_file, rownames=FALSE)
```


Trying to see if I could pull in my notes from an excel file
```{r}

ushe_report <- 'graduation'

notes_on_functions <- read_excel("C:/R folder for github projects/usheUtils/sandbox/excel/rstudio_ushe_project.xlsx",
                       col_types = c("text", "text", "text", "text", "text",
                                     "text", "text", "text", "text", "text",
                                     "text", "text", "text", "text", "text",
                                     "text")) %>% 
  clean_names()

notes_on_functions <- notes_on_functions %>% 
  select(ushe_element, ushe_field, sandbox_function, report) %>% 
  filter(report == ushe_report)


DT::datatable(notes_on_functions, rownames=FALSE)

```

