#' Data of fake_student_df.R
#'
#' A data frame containing ...
#'
#' @format A data frame:
#' \describe{
#'   \item{student_id}{character}
#'   \item{previous_student_id}{character}
#'   \item{ssn}{character}
#'   \item{ssid}{character}
#'   \item{gender_code}{character}
#'   \item{last_name}{character}
#'   \item{first_name}{character}
#'   \item{middle_name}{character}
#'   \item{name_suffix}{character}
#'   \item{previous_last_name}{character}
#'   \item{previous_first_name}{character}
#'   \item{previous_middle_name}{character}
#'   \item{previous_name_suffix}{character}
#'   \item{academic_year_code}{character}
#'   \item{season}{character}
#'   \item{term_start_date}{date}
#'   \item{version_id}{character}
#'   \item{version_date}{date}
#'   \item{census_date}{date}
#'   \item{birth_date}{date}
#'   \item{is_hispanic_latino_ethnicity}{character}
#'   \item{is_asian}{character}
#'   \item{is_black}{character}
#'   \item{is_american_indian_alaskan}{character}
#'   \item{is_hawaiian_pacific_islander}{character}
#'   \item{is_white}{character}
#'   \item{is_international}{character}
#'   \item{is_other_race}{character}
#'   \item{local_address_zip_code}{character}
#'   \item{mailing_address_zip_code}{character}
#'   \item{us_citizenship_code}{character}
#'   \item{first_admit_county_code}{character}
#'   \item{first_admit_country_iso_code}{character}
#'   \item{first_admit_state_code}{character}
#'   \item{residency_code}{character}
#'   \item{primary_major_cip_code}{character}
#'   \item{secondary_major_cip_code}{character}
#'   \item{student_type_code}{character}
#'   \item{primary_level_class_id}{character}
#'   \item{primary_degree_id}{character}
#'   \item{institutional_cumulative_credits_earned}{character}
#'   \item{institutional_cumulative_gpa}{character}
#'   \item{institutional_gpa}{character}
#'   \item{level_id}{character}
#'   \item{total_cumulative_ap_credits_earned}{numeric}
#'   \item{total_cumulative_clep_credits_earned}{numeric}
#'   \item{transfer_cumulative_credits_earned}{numeric}
#'   \item{full_time_part_time_code}{character}
#'   \item{high_school_code}{character}
#'   \item{high_school_graduation_date}{date}
#'   \item{act_science_score}{character}
#'   \item{act_reading_score}{character}
#'   \item{act_math_score}{character}
#'   \item{act_english_score}{character}
#'   \item{act_composite_score}{character}
#'   \item{is_pell_eligible}{character}
#'   \item{is_pell_awarded}{character}
#'   \item{is_bia}{character}
#'   \item{college_desc}{character}
#'   \item{secondary_major_college_id}{character}
#'   \item{primary_major_desc}{character}
#'   \item{secondary_major_desc}{character}
#'   \item{ipeds_award_level_code}{character}
#'   \item{house_bill_75_waiver}{character}
#'   \item{mailing_address_country_code}{character}
#'   \item{local_address_country}{character}
#'   \item{institutional_term_gpa}{character}
#'   \item{secondary_ipeds_award_level_code}{character}
#' }
"fake_student_df"
